[[execbundle]]
arch = "x86_64"
git-tree-sha1 = "b1d94bf40d5b17dcad020f8acacf3694dc0f0864"
os = "linux"

    [[execbundle.download]]
    sha256 = "9b09f718acba657590286209e2ebb2b188503e194e0bb5aba5e3dc7499c2c466"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/linux-x86_64.tar.gz"
[[execbundle]]
arch = "aarch64"
git-tree-sha1 = "dc04e25347c8ebf532842dc63a38a4b230a6e837"
os = "linux"

    [[execbundle.download]]
    sha256 = "e636e40a4e15f21bdc0a786433340d1c460a9a8a48fecb614fb8a8e081dd089a"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/linux-aarch64.tar.gz"
[[execbundle]]
arch = "x86_64"
git-tree-sha1 = "6a207c3e4b5aad8b9841c6005a33204ad9c0a1a7"
os = "macos"

    [[execbundle.download]]
    sha256 = "a7accd147f0acfe2ce55952ef4e88160374e5d079d060bc6c501bfc1f01393a7"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/macos-x86_64.tar.gz"
[[execbundle]]
arch = "aarch64"
git-tree-sha1 = "a94d557443a363252bfb5e650af8baa1189e1de8"
os = "macos"

    [[execbundle.download]]
    sha256 = "49010805c426bbebbced51224f76018448ff5c982f1516a49afe1836e9f22709"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/macos-aarch64.tar.gz"
[[execbundle]]
arch = "x86_64"
git-tree-sha1 = "64a89e9ec88acc7460a08522b947b7c8ea53075b"
os = "freebsd"

    [[execbundle.download]]
    sha256 = "3becc00c4dcfccf53707d63ada2ab7140b6f13e4c2cd21e7987958a7f2f239f2"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/freebsd-x86_64.tar.gz"
[[execbundle]]
arch = "aarch64"
git-tree-sha1 = "bdb0e26eb391327002d6991077ed739f8a4d61f3"
os = "freebsd"

    [[execbundle.download]]
    sha256 = "43901920172fa022c4438e63c835430c60498ba596a0ef8cc7a026c286d0880c"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/freebsd-aarch64.tar.gz"
[[execbundle]]
arch = "arm"
git-tree-sha1 = "1514ffeeb631ec48299c154f0bfc087efbb55c8c"
os = "freebsd"

    [[execbundle.download]]
    sha256 = "945b0e648d2cde66160a341cc33c8487ed78dc6139f5032be46d6a8ea62cdddb"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/freebsd-arm.tar.gz"
[[execbundle]]
arch = "x86_64"
git-tree-sha1 = "91beaa08c325afd8e8d8faf78ad93ae67c231196"
os = "openbsd"

    [[execbundle.download]]
    sha256 = "8ffdb26d018e10c1dbed3b38b94159997750afbdcb7ec8e4e08c717ba523de30"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/openbsd-x86_64.tar.gz"
[[execbundle]]
arch = "aarch64"
git-tree-sha1 = "9cf50814e9fb2c346737d3e6c97516e0fbf312d7"
os = "openbsd"

    [[execbundle.download]]
    sha256 = "f7c53b24075ada91d0f65b1f07ef632c941301d7c82071dd328f7b819f35f323"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/openbsd-aarch64.tar.gz"
[[execbundle]]
arch = "x86_64"
git-tree-sha1 = "3893bf0d6100a4b6703f91745d1af712b836902c"
os = "windows"

    [[execbundle.download]]
    sha256 = "7b4003f86069550d901d29ef2acb88c932eb582a58a13431ee7a5acdae986980"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/windows-x86_64.tar.gz"
[[execbundle]]
arch = "aarch64"
git-tree-sha1 = "718e42311f970116214dfe7582e40d82e420a68c"
os = "windows"

    [[execbundle.download]]
    sha256 = "d1b264cfa1e274c7c7a4c793887376bed1b2ef2ad423531c8d08ec22b5dd3495"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/windows-aarch64.tar.gz"
