[[execbundle]]
arch = "x86_64"
git-tree-sha1 = "b1d94bf40d5b17dcad020f8acacf3694dc0f0864"
os = "linux"

    [[execbundle.download]]
    sha256 = "f07fcd8e701d37b7c087a510fe48055007016fed67f7342954f90190e175687f"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/linux-x86_64.tar.gz"
[[execbundle]]
arch = "aarch64"
git-tree-sha1 = "dc04e25347c8ebf532842dc63a38a4b230a6e837"
os = "linux"

    [[execbundle.download]]
    sha256 = "e0c636b9ab888aa9c0b2a5aa35c064e654e766205dc977077e55a32824c067f6"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/linux-aarch64.tar.gz"
[[execbundle]]
arch = "x86_64"
git-tree-sha1 = "6a207c3e4b5aad8b9841c6005a33204ad9c0a1a7"
os = "macos"

    [[execbundle.download]]
    sha256 = "370fa56230b46c47a06b71ad3fec27c992308c360ca8f4dec5a498af03ef1b3b"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/macos-x86_64.tar.gz"
[[execbundle]]
arch = "aarch64"
git-tree-sha1 = "a94d557443a363252bfb5e650af8baa1189e1de8"
os = "macos"

    [[execbundle.download]]
    sha256 = "2b176c1222469973fd7942ee1ac3ee009d7b169536a964de7d1d8bb44cdb3623"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/macos-aarch64.tar.gz"
[[execbundle]]
arch = "x86_64"
git-tree-sha1 = "64a89e9ec88acc7460a08522b947b7c8ea53075b"
os = "freebsd"

    [[execbundle.download]]
    sha256 = "365ce774adf1c1b606fb234c9b2f66897bdf0fae7c4f27185076f027ce35249b"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/freebsd-x86_64.tar.gz"
[[execbundle]]
arch = "aarch64"
git-tree-sha1 = "bdb0e26eb391327002d6991077ed739f8a4d61f3"
os = "freebsd"

    [[execbundle.download]]
    sha256 = "c4f39df9101c6a40fd0114c20058829dfc7b189587e7463015400250c31e0489"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/freebsd-aarch64.tar.gz"
[[execbundle]]
arch = "arm"
git-tree-sha1 = "1514ffeeb631ec48299c154f0bfc087efbb55c8c"
os = "freebsd"

    [[execbundle.download]]
    sha256 = "58232e826131ce85ea9e122169456a883559780b1d22f5cbe2f3961dae3b9c49"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/freebsd-arm.tar.gz"
[[execbundle]]
arch = "x86_64"
git-tree-sha1 = "91beaa08c325afd8e8d8faf78ad93ae67c231196"
os = "openbsd"

    [[execbundle.download]]
    sha256 = "c04b76850871b32df07a585a5d338d3a52f331c8f1a2aa92d6885d18daa88e8d"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/openbsd-x86_64.tar.gz"
[[execbundle]]
arch = "aarch64"
git-tree-sha1 = "9cf50814e9fb2c346737d3e6c97516e0fbf312d7"
os = "openbsd"

    [[execbundle.download]]
    sha256 = "70e699024fb6d4e5980d7abb8692e31ac3f1ca4808427ea4764681543fcef248"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/openbsd-aarch64.tar.gz"
[[execbundle]]
arch = "x86_64"
git-tree-sha1 = "c71e38c69bed2f0e6cbfd6abe8200543d6e1a0fb"
os = "windows"

    [[execbundle.download]]
    sha256 = "849b9cd620c3c9c4fb1b6a641447e4ff5d4ac8f354084411c300c87660e9aa1f"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/windows-x86_64.tar.gz"
[[execbundle]]
arch = "aarch64"
git-tree-sha1 = "70fa6e2626dbc83ed07cbffe59909f45bb2926bd"
os = "windows"

    [[execbundle.download]]
    sha256 = "cb9c62ef2278390e28f916f77457e647cb8787b8eab89ec63607e7484cedb7aa"
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/windows-aarch64.tar.gz"
